Repository TeamBooJangNim/SanNumSan-WEB, pull requests merged in 2022-05, with the labels that each got.

#8 산 상세 퍼블리싱
  assets/icon/icon_down.svg
  assets/icon/icon_proceed.svg
  assets/icon/icon_share.svg
  assets/icon/icon_up.svg
  next.config.js
  pages/_app.tsx
  pages/san/[id].tsx
  service/api/index.ts
  service/api/san.ts
  service/api/types/san.ts
  service/mock/san.ts
  styles/fonts.scss
  styles/san-detail.scss
Labels: feature 🌊

#9 산 상세 퍼블리싱 - getStaticPaths, getStaticProps
  pages/san/[id].tsx
  service/api/san.ts
  service/mock/san.ts
Labels: help wanted 🐣

#16 등반 인증 기록 링크 공유하기
  next.config.js
  pages/_app.tsx
  pages/san/[sanID]/[proveID].tsx
  pages/san/[sanID]/index.tsx
  service/api/san.ts
  service/api/types/san.ts
  service/mock/san.ts
  styles/prove-detail.scss
Labels: feature 🌊, layout 🔫

#20 [refactor] 산 디테일 그리드 부분을 별도 컴포넌트로 분리, userName을 proveData로부터 받도록 수정
  .vscode/settings.json
  component/BottomSheetModal/BottomSheetModal.scss
  component/FloatingModal/FloatingModal.tsx
  component/Head/Head.tsx
  component/Header/Header.tsx
  component/MainCarousel/CarouselCard.tsx
  component/MainCarousel/CarouselContainer.tsx
  component/MainCarousel/CarouselHeader.tsx
  component/MainCarousel/useCarousel.ts
  component/SanDetailGridView/SanDetailGridView.tsx
  pages/_app.tsx
  pages/counter.tsx
  pages/index.tsx
  pages/san/[sanID]/[proveID].tsx
  pages/san/[sanID]/index.tsx
  service/api/types/san.ts
  service/mock/san.ts
  store/modules/index.ts
  styles/san-detail.scss
Labels: layout 🔫, refacter 🍕
